### PR TITLE
Add "DiffID" to the layer listing

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Here's an example rendering (from `golang:latest`):

---

-	Layers:
	-	`sha256:b111c3320c949bea81612bf4554f1b6592c2f504920b5bf57ba340a1d4d52c93`  
		Size: 1.9 GB (1877166088 bytes)  
		DiffID: `sha256:d6fdd6832d95a5f537e0e7d87f2613ea9741ad9c20438b9d5a2697a883c4cd96`  
		MIME: application/vnd.docker.image.rootfs.foreign.diff.tar.gzip
	-	`sha256:294d77ac553d7210b662d07674ef9e39a6c2e88dc15b9d2788d51e509bc8b54e`  
		Size: 800.5 MB (800546641 bytes)  
		DiffID: `sha256:ccc004b169ee6b7194527fa6d6b7426e2943474955f102a36dfa9570705b2d60`  
		MIME: application/vnd.docker.image.rootfs.foreign.diff.tar.gzip
	-	`sha256:d64f32398ff5e4ac4cbab317ffed87a2fbf4e4a37210284dba19f2929d631a95`  
		Last Modified: Wed, 10 Aug 2022 12:42:57 GMT  
		Size: 1.4 KB (1430 bytes)  
		DiffID: `sha256:7c01b84090896fffa209fcd821a841b91dac0ea2e465fe68c1589a7bc2f82c14`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip
	-	`sha256:da3c8de3c3b75d5e4df16d5b51d2629a7ea48fef427269b895425ddf83e4648f`  
		Last Modified: Wed, 10 Aug 2022 13:25:13 GMT  
		Size: 1.4 KB (1419 bytes)  
		DiffID: `sha256:2fcd10c3f5bb381a59cd8de222f364988c78fa7d67e5d21cd82bac086a49b214`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip
	-	`sha256:1379e9d7c93c53a7225d517ef3bbf5ac5db662822c6b033ba0f86e57f553f9f1`  
		Last Modified: Wed, 10 Aug 2022 13:25:10 GMT  
		Size: 1.4 KB (1423 bytes)  
		DiffID: `sha256:a71cf20e012df12e283c9ebae7495c381ef56d909fe69229ff0b57608e3c5594`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip
	-	`sha256:7c04c4fbebbd0c6b7ec0d088c9f85358565ade6536be3c27ec839439c70b3300`  
		Last Modified: Wed, 10 Aug 2022 13:25:10 GMT  
		Size: 1.4 KB (1417 bytes)  
		DiffID: `sha256:a1c6897719f127fab07c7224d28384dd28675dafe01cac80950f365b9202bb7a`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip
	-	`sha256:345f3fbeaf81942e1e576c351394bee7910b1bd200d739562499849161810b00`  
		Last Modified: Wed, 10 Aug 2022 13:25:09 GMT  
		Size: 1.4 KB (1412 bytes)  
		DiffID: `sha256:8916786360f3a07bdafaf916b656594bfa9e1a2661202bb989ce4ee78cd094cc`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip
	-	`sha256:9daa4ce5f809aaf1eb408a95c9c6bb87f8b8971efb28085fb12419172bc3769b`  
		Last Modified: Wed, 10 Aug 2022 13:25:17 GMT  
		Size: 25.4 MB (25441513 bytes)  
		DiffID: `sha256:1b4d6d2d2eeb63c0889b99ecf086f76a30ccce435fbea8d0337f6f4524653971`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip
	-	`sha256:94a64bd2b96a29fef52e63363ec6219a5a846d18825d515fdd5c5a45d62eaf71`  
		Last Modified: Wed, 10 Aug 2022 13:25:07 GMT  
		Size: 1.4 KB (1422 bytes)  
		DiffID: `sha256:d36d9cd08eb3176267789bd3c4061c60c42ea702c556f6a79a38ee0a7455df2c`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip
	-	`sha256:db4ccb61f1f7e4a0d3ecd876f61280913525a4ef70cc4b82b16a164f4fe7f982`  
		Last Modified: Wed, 10 Aug 2022 13:25:07 GMT  
		Size: 315.2 KB (315177 bytes)  
		DiffID: `sha256:76a3a2e5e41c83bde74c275853d93b11cc6b235ae4eea4d02d6caed33488bba4`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip
	-	`sha256:e01fd09706e986a5b233efd7b3c784b3b140f0eca2f0f29e17c1c5e3109a0727`  
		Last Modified: Wed, 10 Aug 2022 13:25:07 GMT  
		Size: 1.4 KB (1426 bytes)  
		DiffID: `sha256:5686dec61308c26d5126fe50459ae67f6195667e9bbc470e997c0020caee8812`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip
	-	`sha256:1aa455d8815fa04892b104fb76b8ae072872a55a69ec1617d311d4f093e52f27`  
		Last Modified: Wed, 10 Aug 2022 13:26:00 GMT  
		Size: 157.5 MB (157534853 bytes)  
		DiffID: `sha256:b3f924986ccc3320e08696c51991aad21b1d1e41be4be76c07c73a748d914748`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip
	-	`sha256:b3e1f95133cea3ac7fb16f81eb7e614f14b842926e28028548c7d231b24d943b`  
		Last Modified: Wed, 10 Aug 2022 13:25:07 GMT  
		Size: 1.6 KB (1579 bytes)  
		DiffID: `sha256:b519b7340003c77047c8830e247989017e22bdd9d8806d2bf3779a0e4113a7ce`  
		MIME: application/vnd.docker.image.rootfs.diff.tar.gzip

**Comment by cdupuis** [comment]
This looks great @tianon. Thanks!

**Comment by yosifkit** [comment]
:confused: I'm not certain we should add even more data here; this repo is very much a hack of things that either ought to be exposed in a database or registry API, or presented in a friendly user interface. Creating more data for an automated user in our unstructured markdown should not be the focus.

**Comment by tianon** [comment]
Yeah, good point -- I got so caught up in "yes, I can add this to our data!" and excitedly implementing it that I didn't think about the purpose of this repository and how `diff_ids` doesn't really fit that. :sweat_smile:

**Pull request closed without merging**
